[provider]
id = "python"

[python]
version = "3.11"

[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y ffmpeg imagemagick poppler-utils ghostscript libmagic1 libreoffice",
    "apt-get clean",
    "python -m pip install --upgrade pip",
]

[phases.install]
cmds = [
    "pip install --no-cache-dir -r requirements.txt",
]

[phases.build]
cmds = [
    "echo 'Build completed successfully'",
]

[start]
cmd = "python bot.py"